from pathlib import Path
import json
root=Path(__file__).resolve().parent
copy=json.loads((root.parent/'copy.json').read_text())
favorites={
 'tr':['Favori radyoların','Sevdiğin istasyonlara kolayca ulaş'],
 'de-DE':['Deine Lieblingssender','Schnell finden. Direkt einschalten.'],
 'en-US':['Your favorite stations','Save them. Find them. Press play.'],
 'en-GB':['Your favourite stations','Keep the radio you love close'],
 'en-AU':['Your favourite stations','Local favourites. A world of radio.'],
 'en-CA':['Your favourite stations','From local radio to the world'],
 'fr-FR':['Vos radios favorites','Retrouvez vos stations en un instant'],
 'fr-CA':['Vos radios préférées','Vos stations du Québec et d’ailleurs'],
 'es-ES':['Tus emisoras favoritas','Encuentra tu radio y dale al play'],
 'es-MX':['Tus estaciones favoritas','Tu radio de siempre, a un toque'],
 'pt-PT':['As tuas rádios favoritas','Encontra a tua estação e começa a ouvir'],
 'pt-BR':['Suas rádios favoritas','Salve suas emissoras e dê o play'],
 'it':['Le tue radio preferite','Ritrovale e mettiti in ascolto'],
 'nl-NL':['Je favoriete zenders','Bewaar ze en luister meteen'],
 'sv':['Dina favoritkanaler','Spara och hitta tillbaka direkt'],
 'no':['Dine favorittkanaler','Lagre dem og lytt når du vil'],
 'da':['Dine favoritkanaler','Gem dem, og lyt med det samme'],
 'fi':['Suosikkikanavasi','Tallenna ja löydä helposti uudelleen'],
 'pl':['Twoje ulubione stacje','Zapisz je i wracaj do słuchania'],
 'cs':['Oblíbené stanice','Uložte si je a snadno je najděte'],
 'sk':['Obľúbené stanice','Uložte si ich a počúvajte znova'],
 'hu':['Kedvenc rádióid','Mentsd el, és hallgasd újra'],
 'ro':['Posturile tale preferate','Salvează-le și ascultă ușor'],
 'hr':['Omiljene postaje','Spremite ih i jednostavno slušajte'],
 'el':['Οι αγαπημένοι σου σταθμοί','Αποθήκευσε και άκουσε εύκολα'],
 'ru':['Любимые радиостанции','Сохраните и находите их быстрее'],
 'uk':['Улюблені радіостанції','Зберігайте та знаходьте їх швидше'],
 'ca':['Les teves ràdios preferides','Desa-les i torna-hi fàcilment'],
 'ar-SA':['محطاتك المفضلة','احفظ محطاتك واعثر عليها بسهولة'],
 'he':['תחנות הרדיו האהובות','שמרו אותן וחזרו להאזין בקלות'],
 'ja':['お気に入りのラジオ局','保存した放送局にすぐアクセス'],
 'zh-Hans':['收藏喜爱的电台','轻松找到，随时收听'],
 'zh-Hant':['收藏喜愛的電台','輕鬆找到，隨時收聽'],
 'ko':['즐겨찾는 라디오 방송','저장하고 간편하게 다시 듣기'],
 'id':['Stasiun favoritmu','Simpan dan dengarkan dengan mudah'],
 'ms':['Stesen kegemaran anda','Simpan dan dengar dengan mudah'],
 'th':['สถานีโปรดของคุณ','บันทึกไว้แล้วกลับมาฟังได้ง่าย'],
 'vi':['Đài phát thanh yêu thích','Lưu lại và tìm nghe dễ dàng'],
 'hi':['आपके पसंदीदा स्टेशन','सहेजें और आसानी से फिर सुनें'],
 'bn':['আপনার পছন্দের স্টেশন','সংরক্ষণ করুন, সহজে আবার শুনুন'],
 'gu':['તમારા મનપસંદ સ્ટેશન','સાચવો અને સરળતાથી ફરી સાંભળો'],
 'kn':['ನಿಮ್ಮ ನೆಚ್ಚಿನ ನಿಲ್ದಾಣಗಳು','ಉಳಿಸಿ ಮತ್ತು ಸುಲಭವಾಗಿ ಮತ್ತೆ ಕೇಳಿ'],
 'ml':['നിങ്ങളുടെ പ്രിയപ്പെട്ട നിലയങ്ങൾ','സൂക്ഷിച്ച് എളുപ്പത്തിൽ വീണ്ടും കേൾക്കൂ'],
 'mr':['तुमची आवडती केंद्रे','जतन करा आणि सहज पुन्हा ऐका'],
 'or':['ଆପଣଙ୍କ ପସନ୍ଦର ଷ୍ଟେସନ୍','ସଞ୍ଚୟ କରନ୍ତୁ ଏବଂ ସହଜରେ ପୁଣି ଶୁଣନ୍ତୁ'],
 'pa':['ਤੁਹਾਡੇ ਮਨਪਸੰਦ ਸਟੇਸ਼ਨ','ਸੰਭਾਲੋ ਅਤੇ ਆਸਾਨੀ ਨਾਲ ਦੁਬਾਰਾ ਸੁਣੋ'],
 'ta':['உங்கள் பிடித்த நிலையங்கள்','சேமித்து எளிதாக மீண்டும் கேளுங்கள்'],
 'te':['మీకు ఇష్టమైన స్టేషన్లు','సేవ్ చేసి సులభంగా మళ్లీ వినండి'],
 'ur':['آپ کے پسندیدہ اسٹیشن','محفوظ کریں اور آسانی سے دوبارہ سنیں'],
 'sl':['Vaše priljubljene postaje','Shranite jih in preprosto poslušajte']}
assert set(favorites)==set(copy)
result={loc:{'discover':[a['name'].replace('MegaRadio: ',''),a['subtitle']],'favorites':favorites[loc]} for loc,a in copy.items()}
(root/'captions.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
print('50 localized screenshot caption sets')
